### ISSUE TITLE
Convert Holistic to BlazePose+Hands

### ISSUE THREAD

**Issue by GokulNC** [AI4Bharat/OpenHands#17]
Holistic just seems to be BlazePose+Hands+FaceMesh.
For faster generation of keypoints, better use the first 2 itself as in INCLUDE repo.

**Comment by AmitMY** [comment]
fyi, holistic graph performs hand cropping based on the blazepose, no hands detection model needed

**Comment by GokulNC** [comment]
Did not know that, thanks!
