### ISSUE TITLE
inward_edges for ST-GCN training with mediapipe_holistic_top_body_59 

### ISSUE THREAD

**Issue by EmpyEmpt** [AI4Bharat/OpenHands#47]
Hello!

I was wondering if there was an inward_edges layout for training ST-GCN with mediapipe_holistic_top_body_59? There doesn't seem to be any in examples or documentation. 
If you do not have one, is there some sort of mapping for mediapipe_holistic_top_body_59 and mediapipe_holistic_minimal_27, so we could build it ourselfs?

Thanks in advance

**Comment by Prem-kumar27** [comment]
Hey @EmpyEmpt Thanks for your interest in the library!

We used the below edges mapping for 59 keypoints:

```
[(0,1),(1,2),(1,3),(3,7),
(0,4),(4,5),(5,6),(6,8),
(0,9),(0,10),(9,11),(10,12),
(11,13),(13,17),(17,18),(18,19),(19,20),(20,21),(17,22),(22,23),(23,24),(24,25),
(17,26), (26,27),(27,28),(28,29),(17,30),(30,31),(31,32),(32,33),
(17,34),(34,35),(35,36),(36,37),
(12,14),(14,38),(38,39),(39,40),(40,41),(41,42),
(38,43),(43,44),(44,45),(45,46),(38,47),(47,48),(48,49),(49,50), (38,51),(51,52),(52,53),(53,54),
(38,55),(55,56),(56,57),(57,58),
(11,15),(12,16),(15,16)]
```

You can probably try this

**Comment by EmpyEmpt** [comment]
Yeap, great library! Thanks for running it open-source! 

Your mapping works great! I think you should post it in some exaple or in the docs
