### ISSUE TITLE
'WLASLDataset' object has no attribute '__getitem_pose'

### ISSUE THREAD

**Issue by BobbyLilD** [AI4Bharat/OpenHands#48]
Hello! I'm trying trying to run inference using a pretrained SL-GCN model and I keep getting an error:
`AttributeError: 'WLASLDataset' object has no attribute '__getitem_pose'`

Library version is 0.1.4.1. What could be the cause of the problem?

**Comment by GokulNC** [comment]
Sorry for the delayed response, and thanks for closing this issue.
What was the cause of the problem?

**Comment by BobbyLilD** [comment]
I haven’t really gotten to the root of it, but it definitely has something to do with multiprocessing since I've fixed it by removing the num_workers parameter in the dataloader section of the config.
